#%RAML 1.0
title: MuleSoft IDP Universal 🌐 Process API
version: v1
mediaType: application/json
protocols: HTTPS

baseUri: https://{host}/api/{version}
baseUriParameters:
  host:
    type: string
    example: mulesoft-idp-universal-process-app-uupas5.m3jzw3-1.deu-c1.cloudhub.io
    default: mulesoft-idp-universal-process-app-uupas5.m3jzw3-1.deu-c1.cloudhub.io

/idp/actions/{actionId}/versions/{actionVersion}/executions:
  uriParameters:
    actionId:
      type: field-actionId
    actionVersion:
      type: field-actionVersion

  post:
    is: [client-id-required]
    displayName: 🤖 IDP postDocumentActionExecution
    description: Submits a file for IDP processing
    queryParameters:
      mode:
        description: Mode
        displayName: Mode
        enum:
          - requestAndReply
          - eventDrivenArchitecture
        default: requestAndReply
        example: requestAndReply
        type: string
        required: true

    body:
      application/json:
        properties:
          contentBase64:
            description: encode the file content in base64
            example: JVBERi0xLjcNCiWhs8XXDQoxIDAgb......
            type: string
            required: true
          fileNameAndExtension:
            description: File Name to be Processed https://docs.mulesoft.com/idp/quotas-and-limits
            default: IDP-PO-CD656092-BurlingtonTextiles.pdf
            example: IDP-PO-CD656092-BurlingtonTextiles.pdf
            type: string
            required: true
          msc:
            type: field-msc
            required: false
      multipart/form-data:
        properties:
          fileContent:
            description: fileContent has the actual payload.
            type: file
            fileTypes: ['application/pdf','image/png', 'image/jpeg']
            required: true

    responses:
      201:
        description: Created
        body:
          application/json: object-DocumentExecutionPostResponse
      400:
        description: Bad Request
        body:
          application/problem+json:
            type: object-commonError
      406:
        description: Not Acceptable
        body:
          application/problem+json:
            type: object-commonError
      500:
        description: Internal Server Error
        body:
          application/problem+json:
            type: object-commonError

  /{executionId}:
    uriParameters:
      executionId:
        type: field-executionId
    get:
      is: [client-id-required]
      displayName: 🤖 IDP getDocumentActionExecution
      description: Retrieves the State & Result Data of a document action execution.
      queryParameters:
        valueOnly:
          description: 🚨 Un-supported so use with Caution - Return Confidence levels when set to false
          type: string
          enum: # Bug in portal with Boolean
            - "false"
            - "true"
          required: false
      responses:
        200:
          description: Success
          body:
            application/json: object-DocumentExecutionGetResponse
        404:
          description: Not Found
          body:
            application/problem+json:
              type: object-commonError
        406:
          description: Not Acceptable
          body:
            application/problem+json:
              type: object-commonError
        429:
          description: Too Many Requests
          body:
            application/problem+json:
              type: object-commonError

traits:
  client-id-required:
    description: 🛡️ MuleSoft Client ID Enforcement
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error

types:

  field-actionId:
    displayName: IDP Document Action Id
    description: Published Document Action UUID
    default: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    example: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    type: string
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$

  field-actionVersion:
    displayName: IDP Document Action Id Version
    description: Document Action Version like 1.0.0
    default: 1.1.0
    example: 1.1.0
    type: string
    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$

  field-msc:
    displayName: IDP Document Action Msc
    description: Save Msc Info
    example: my case key
    type: string


  field-executionId:
    displayName: IDP Execution Id
    description: IDP Execution Id returned after successful submission
    default: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    example: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    type: string
    pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$

  field-ExecutionStatus:
    displayName: IDP Execution Status
    description: |
      ## [Execution Results Reference](https://docs.mulesoft.com/idp/automate-document-processing-with-the-idp-api#execution-status-reference).

      When you query the results of an execution, the IDP API returns the status which can be any of the following:

      - `ACKNOWLEDGED`: The document action execution request was received.
      - `IN_PROGRESS`: The execution started.
      - `RESULTS_PENDING`: The execution finished and IDP is processing the results.
      - `MANUAL_VALIDATION_REQUIRED`: The execution finished but the results need manual validation.
      - `FAILED`: The execution request finished unsuccessfully.
      - `PARTIAL_SUCCESS`: The execution request finished but some sub-tasks failed.
      - `SUCCEEDED`: The execution request finished successfully.
    default: IN_PROGRESS
    enum:
      - ACKNOWLEDGED
      - IN_PROGRESS
      - RESULTS_PENDING
      - MANUAL_VALIDATION_REQUIRED
      - FAILED
      - PARTIAL_SUCCESS
      - SUCCEEDED
    example: IN_PROGRESS
    type: string

  object-DocumentExecutionPostResponse:
    displayName: IDP Document Submission Response Object
    description: 
    type: object
    properties:
      id:
        type: field-executionId
        required: true
      documentName:
        description: Document Name and Extension
        type: string
        example: IDP-PO-CD656092-BurlingtonTextiles.pdf
        required: true
      status:
        type: field-ExecutionStatus
        required: false
    additionalProperties: false
    example: {"id": "af78b8b2-3867-4073-aac6-d24e01f48ae2","documentName": "IDP-PO-CD656092-BurlingtonTextiles.pdf"}

  object-DocumentExecutionGetResponse:
    displayName: IDP Retrieve Execution Response Object
    type: object
    description:
    properties:
      pages?:
        type: array
        items: Page
      id?:
        type: field-executionId
      documentName?:
        type: string
      prompts?:
        type: Prompt
      status?:
        type: field-ExecutionStatus
  Page:
    displayName: IDP Retrieve Execution Response Page Object
    type: object
    properties:
      tables?:
        type: object
        properties: {}
      page?:
        type: string
      fields?:
        type: object
        properties: {}
      prompts?:
        type: Prompt
  Prompt:
    displayName: IDP Retrieve Execution Response Prompt Object
    type: object
    properties:
      answer?: Field
      source?:
        type: string
      prompt?:
        type: string
  Field:
    displayName: IDP Retrieve Execution Response Field Object
    type: object
    properties:
      value?:
        type: string
      geometry?:
        type: object
        properties:
          height:
            type: number
            required: false
          left:
            type: number
            required: false
          width:
            type: number
            required: false
          top:
            type: number
            required: false
      confidenceScore?:
        type: number

  object-commonError:
    displayName: 🆘 IDP Common Error Response
    description: IDP Common Error Response
    properties:
      status:
        description: HTTP response status codes
        default: 404
        example: 404
        type: number
        format: int
        required: true
      title:
        description: Error Title
        example: Not Found
        type: string
        required: true
      detail:
        description: Error Details if available
        example: "Action Id: 90c3e286-72b5-42ca-92d0-22f86ea8d766, Version: 1.1.0, Execution Id: 022c61de-9bfc-4a94-8a9c-43c5f8ac1531"
        type: string
        required: false
    example: {"status": 404,"title": "Not Found"}
    additionalProperties: false

description: |

  

  mediaType: application/json

  protocols: HTTPS

  securedBy: 🛡️ MuleSoft Client ID Enforcement

  | Author | Date | Description
  | -------- | ------- | ------- |
  | G.Jeffcock | 23rd June 2024 | Launched| 
  |||| 
  ||||

  - **getDocumentActionExecution** Retrieves the result of a document action execution.
  - **postDocumentActionExecution** Submits a document to IDP for processing.

documentation:
 - title: 📌 Why?
   content: |
     ### MuleSoft IDP Universal 🌐 REST Connector 🔌

 - title: 📌 How?
   content: |
     ### MuleSoft IDP Universal 🌐 REST Connector 🔌
